php1:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

php2:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

php3:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

php4:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

php5:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

php6:
  build: .
  dockerfile: build/Dockerfile.php-fcgi
  expose:
    - "9009"
  volumes:
    - .:/var/www/html

web:
  build: .
  dockerfile: build/Dockerfile.nginx-fastcgi
  links:
    - php1
    - php2
    - php3
    - php4
    - php5
    - php6
  ports:
    - 80:80
  volumes:
    - .:/var/www/html
